sudo: required
language: node_js
node_js:
  - "0.10"

before_install:
  - "curl https://install.meteor.com | /bin/sh"

script:
  - meteor add rocketchat:external
  - meteor add rocketchat:hubot
  - meteor build --server demo.rocket.chat ./